### ISSUE TITLE
Page size for memory allocation may be to small

### ISSUE THREAD

**Issue by SaschaWillems** [RCalocaO/VkTest#1]
Just ran into a crash on an AMD GPU running this caused by the default page size being smaller than the actual alloctation size from the memory requirements for the depth attachment:

![image](https://cloud.githubusercontent.com/assets/10283127/17929477/16c96bf2-6a01-11e6-8bbf-66ac2ed82d75.png)

For this depth format the alignment is pretty wide, resulting in a memory allocation size that's bigger than the page max. page size resulting in the allocation failing. Default window size requested by the application was 1904x970. 

To make this work I guess you'd either have to dial up the page size (which was the quick fix I used to get this running :wink: ) or allocate multiple pages.

**Comment by RCalocaO** [comment]
Nice catch!
I need to spent more than 10min per sitting to fix this properly and share memory correctly (including the alignment so I can share buffers and images :)
Thanks!

**Comment by RCalocaO** [comment]
Fixed!
